spring:
  datasource:
    url: jdbc:mysql://localhost:3306/football_manager
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
  logging:
    level:
      root: info
    log4j2:
      config-location: classpath:log4j2.xml

